#!/bin/bash
#PBS -N assignment2_partA_profile
#PBS -l select=1:ngpus=1
#PBS -l walltime=01:00:00
#PBS -q normal
#PBS -j oe

module load cuda/12.2.2

cd /home/users/ntu/c230179/Desktop/SC4064/Assignment\ 2 || exit 1

nvcc -O3 -lineinfo -std=c++17 -DPART_A_PROFILE_MODE=1 -o part_a_wave_profile part_a_wave.cu
ncu --set speedOfLight --section LaunchStats --target-processes all --profile-from-start off --force-overwrite true --export part_a_profile ./part_a_wave_profile
